In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/content/tested.csv')

In [5]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [6]:
df.shape

(418, 12)

In [7]:
df.dropna(inplace=True)

In [8]:
X = df.loc[:,['Age','Fare']]
y = df.loc[:,['Survived']]

In [9]:
y = y.to_numpy().ravel()

In [10]:
X

Age      Fare
12   23.0   82.2667
14   47.0   61.1750
24   48.0  262.3750
26   22.0   61.9792
28   41.0   30.5000
..    ...       ...
404  43.0   27.7208
405  20.0   13.8625
407  50.0  211.5000
411  37.0   90.0000
414  39.0  108.9000

[87 rows x 2 columns]

In [11]:
y

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [12]:
from sklearn.linear_model import Perceptron

In [13]:
p = Perceptron()

In [14]:
X.isnull().sum()

Age     0
Fare    0
dtype: int64

In [15]:
p.fit(X,y)

Perceptron()

In [17]:
p.coef_

array([[-58.    , 276.0632]])

In [18]:
p.intercept_

array([-10.])